services:
  web:
    build: .
    container_name: express_app
    restart: always
    ports:
      - "3000:3000"                 # Expose the app on port 3000
    environment:
      SECRET_KEY: 6fe8b6f123f6d8a948b243bacb929f834dceea95b8a513389b2c758f15fa0213
    volumes:
      - .:/app                      # Mount the application code
      - sqlite-data:/app/database   # Persistent volume for SQLite database
    command: node server.js         # Start the Express app
    networks:
      - app-network

volumes:
  sqlite-data:                      # Volume for SQLite database

networks:
  app-network:
    driver: bridge
